name: Auto-approve PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'hughcrt' || github.event.pull_request.user.login == 'vincelwt'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Auto-approve PR
        continue-on-error: true
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.LUNARY_BOT_GH_TOKEN }}
      - name: Always succeed
        run: exit 0
