name: Run tests
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Setup application
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start backend and frontend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          APP_URL: http://0.0.0.0:8080
          API_URL: http://0.0.0.0:3333
          LUNARY_PUBLIC_KEY: 259d2d94-9446-478a-ae04-484de705b522
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEXT_PUBLIC_API_URL: http://0.0.0.0:3333
        timeout-minutes: 3
        run: |
          npm run migrate:db
          npm run start:backend &
          npm run dev:frontend &
          npx wait-on http://localhost:3333/v1/health http://0.0.0.0:8080/

      - name: Run tests
        run: npm run test
        env:
          BASE_URL: http://0.0.0.0:8080
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30
