name: Update and Publish Helm Chart

on:
  release:
    types: [published]

jobs:
  update-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the lunary repo
        uses: actions/checkout@v4
        with:
          path: lunary

      - name: Check out the helm repo
        uses: actions/checkout@v4
        with:
          repository: lunary-ai/helm
          token: ${{ secrets.GH_TOKEN }}
          path: helm

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Login to Helm registry
        run: |
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Remove 'v' prefix from release tag
        id: release_tag
        run: echo "tag=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: Update Helm chart
        working-directory: helm
        run: |
          bash update ${{ steps.release_tag.outputs.tag }}

      - name: Publish Helm chart
        working-directory: helm
        run: |
          bash publish

      - name: Commit and push changes
        working-directory: helm
        run: |
          git config --local user.email "chocart.hugues@icloud.com"
          git config --local user.name "hughcrt"
          git add .
          git commit -m "chore: update Helm chart to version ${{ steps.release_tag.outputs.tag }}"
          git push
